"""
SignalGraph — Explain-Only Chat Assistant
===========================================
Exposes: answer_question(message: str, history: list[dict]) -> str

Converses about the 20 companies in SignalGraph's tracked universe —
current price, sector, comparisons between stocks, sector overviews,
what a severity/signal means, and natural follow-ups ("what about its
volume?") — grounded in a live snapshot of the actual database pulled
fresh on every call, and using `history` to recall which instrument
was last discussed so a user doesn't have to repeat the ticker every
turn.

Zero-cost by default: without ANTHROPIC_API_KEY configured, every
answer comes from a fully deterministic, template-based engine — no
external API call, no charge, ever. It can't do true open-ended
understanding the way an LLM can (novel phrasing outside its known
intents falls through to a generic help message), but its intent
coverage is deliberately broad: greetings, thanks, capability
questions, per-instrument/comparison/sector answers, aspect-focused
follow-ups (price/volume/sector/signal), and a market summary. If
ANTHROPIC_API_KEY IS configured, answers are generated by Claude
instead for genuinely open-ended conversation, using the exact same
data and the exact same hard boundary below.

Hard boundary, enforced in both paths: this assistant explains what
happened, never what to do about it. No buy/sell/hold calls, no price
targets, no investment advice of any kind. In the rule-based path this
is a keyword gate checked before anything else runs — before intent
matching, before history lookback — so it can't be talked around by
phrasing or by steering the conversation there gradually across turns;
in the LLM path it's the system prompt.
"""

import re

from app.config import ANTHROPIC_API_KEY
from app.db import supabase

MODEL = "claude-opus-5"

ADVICE_KEYWORDS = [
    "should i buy", "should i sell", "worth buying", "worth investing",
    "good investment", "invest in", "buy or sell", "recommend",
    "target price", "price target", "will it go up", "will it go down",
    "predict", "forecast", "any tips", "give me a tip", "advice on",
    "good time to buy", "good time to sell", "good time to invest",
    "should i invest", "best stock to buy", "which stock should",
    "is it a good buy", "buy now", "sell now",
]

NO_ADVICE_REPLY = (
    "I can only explain what's already happened with these stocks — price moves, volume "
    "spikes, and why a signal fired — not what to do about it. I can't give investment "
    "advice, price targets, or buy/sell recommendations. For that, please consult a "
    "licensed financial advisor."
)

GREETING_PATTERN = re.compile(r"^\s*(hi|hello|hey|yo|good morning|good afternoon|good evening)\b", re.I)
THANKS_PATTERN = re.compile(r"\b(thanks|thank you|thx|appreciate it)\b", re.I)
FAREWELL_PATTERN = re.compile(r"^\s*(bye|goodbye|see ya|see you|later|cya)\b", re.I)
SHORT_MESSAGE_WORD_LIMIT = 5  # a greeting/farewell longer than this is probably part of a real question too
CAPABILITY_PATTERN = re.compile(r"\b(what can you do|what do you know|help me|how (can|do) (you|i) (use|help)|who are you|what are you)\b", re.I)
SEVERITY_PATTERN = re.compile(r"\b(what.{0,3}s? (a |the )?severity|what does severity mean|what.{0,3}s? a signal|how (does|do) (this|signals?|severity) work|what.{0,3}s? (high|medium|low) (mean|classification))\b", re.I)

SECTOR_ALIASES = {
    "Information Technology": ["information technology", "it sector", "tech sector", "technology sector"],
    "Banking": ["banking sector", "banking", "bank stocks", "the banks"],
    "Energy and Utilities": ["energy sector", "energy and utilities", "utilities sector", "oil and gas", "power sector"],
    "Consumer Goods": ["consumer goods", "fmcg", "consumer sector"],
    "Automotive": ["automotive sector", "auto sector", "automobile sector", "auto stocks"],
}

FOCUS_KEYWORDS = {
    "volume": ["volume", "trading volume"],
    "price": ["price", "cost", "worth", "trading at"],
    "sector": ["sector", "industry"],
    "signal": ["signal", "severity", "classification", "flagged"],
}

FOLLOWUP_HINT_PATTERN = re.compile(r"\b(it|its|that|this one|what about|and its|and the)\b", re.I)

GREETING_REPLY = (
    "Hi! I can talk about the 20 stocks SignalGraph tracks — price, sector, comparisons, "
    "or why a signal fired — but I can't give investment advice. What would you like to know?"
)
FAREWELL_REPLY = "Take care! Come back anytime you want to know what's moving in your watchlist."
CAPABILITY_REPLY = (
    "I can tell you about any of the 20 stocks SignalGraph tracks: current price, sector, "
    "why a signal fired, comparisons between two or three stocks, or a sector overview "
    "(\"how's the IT sector doing?\"). I can't give investment advice, price targets, or "
    "buy/sell recommendations — just explain what already happened."
)
SEVERITY_REPLY = (
    "Severity is a 0-100 score SignalGraph computes for each stock from four things: how "
    "unusual its price move was, how unusual its trading volume was, how differently it "
    "moved from its sector peers, and whether it broke a recent high or low. HIGH means "
    "70 or above, MEDIUM means 40 or above, LOW means 20 or above, and anything below 20 "
    "isn't flagged as a signal at all."
)


def _is_advice_seeking(message: str) -> bool:
    msg = message.lower()
    return any(kw in msg for kw in ADVICE_KEYWORDS)


def _find_mentioned_instruments(message: str, instruments: list[dict]) -> list[dict]:
    """All distinct instruments mentioned, in order of first appearance —
    used both for single-instrument answers and multi-instrument comparisons."""
    msg = message.lower()
    found: list[dict] = []
    seen_ids = set()

    for inst in instruments:
        ticker_short = inst["ticker"].replace(".NS", "").lower()
        if re.search(rf"\b{re.escape(ticker_short)}\b", msg) and inst["id"] not in seen_ids:
            found.append(inst)
            seen_ids.add(inst["id"])

    for inst in instruments:
        if inst["id"] in seen_ids:
            continue
        name_words = [w.lower() for w in inst["name"].split() if len(w) > 3]
        if any(re.search(rf"\b{re.escape(w)}\b", msg) for w in name_words):
            found.append(inst)
            seen_ids.add(inst["id"])

    return found


def _find_mentioned_sector(message: str) -> str | None:
    msg = message.lower()
    for sector, aliases in SECTOR_ALIASES.items():
        if any(alias in msg for alias in aliases):
            return sector
    return None


def _detect_focus(message: str) -> str | None:
    msg = message.lower()
    for focus, keywords in FOCUS_KEYWORDS.items():
        if any(kw in msg for kw in keywords):
            return focus
    return None


def _looks_like_followup(message: str) -> bool:
    return bool(FOLLOWUP_HINT_PATTERN.search(message))


def _last_mentioned_instrument(history: list[dict], instruments: list[dict]) -> dict | None:
    for turn in reversed(history):
        found = _find_mentioned_instruments(turn.get("content", ""), instruments)
        if found:
            return found[0]
    return None


def _instrument_answer(inst: dict, focus: str | None = None) -> str:
    stats_rows = supabase.table("instrument_stats").select("*").eq("instrument_id", inst["id"]).execute().data
    stats = stats_rows[0] if stats_rows else None

    signal_rows = (
        supabase.table("signals")
        .select("*")
        .eq("instrument_id", inst["id"])
        .order("event_time", desc=True)
        .limit(1)
        .execute()
        .data
    )
    signal = signal_rows[0] if signal_rows else None
    ticker_short = inst["ticker"].replace(".NS", "")

    if focus == "sector":
        return f"{inst['name']} ({ticker_short}) is in the {inst['sector']} sector."

    if focus == "price":
        if stats and stats.get("last_price") is not None:
            return f"{ticker_short}'s last known price is {stats['last_price']}."
        return f"I don't have price data for {ticker_short} yet."

    if focus == "volume":
        if signal:
            vol_reason = next(
                (r for r in (signal.get("explanation") or {}).get("reasons", []) if "volume" in r.lower()),
                None,
            )
            if vol_reason:
                return f"For {ticker_short}: {vol_reason}"
        return f"Nothing unusual about {ticker_short}'s trading volume recently."

    if focus == "signal":
        if signal:
            explanation = signal.get("explanation") or {}
            return (
                f"{ticker_short}'s most recent signal was {explanation.get('classification', 'unknown')} "
                f"severity ({signal['severity']})."
            )
        return f"No signal has been detected for {ticker_short} recently."

    # No specific focus — the full picture.
    parts = [f"{inst['name']} ({ticker_short}) is in the {inst['sector']} sector."]
    if stats and stats.get("last_price") is not None:
        parts.append(f"Last known price: {stats['last_price']}.")
    else:
        parts.append("No price data is available for it yet.")

    if signal:
        explanation = signal.get("explanation") or {}
        classification = explanation.get("classification", "unknown")
        reasons = explanation.get("reasons") or []
        if reasons:
            parts.append(
                f"The most recent detected signal was {classification} severity "
                f"({signal['severity']}): {'; '.join(reasons)}"
            )
        else:
            parts.append(
                f"The most recent detected signal was {classification} severity "
                f"({signal['severity']}), with no specific reasons recorded."
            )
    else:
        parts.append("No unusual price, volume, or sector-divergence behavior has been detected for it recently.")

    return " ".join(parts)


def _comparison_answer(insts: list[dict], focus: str | None = None) -> str:
    tickers = ", ".join(i["ticker"].replace(".NS", "") for i in insts)
    parts = [f"Comparing {tickers}:"]
    for inst in insts:
        parts.append("- " + _instrument_answer(inst, focus))
    return "\n".join(parts)


def _sector_answer(sector: str, instruments: list[dict]) -> str:
    sector_instruments = [i for i in instruments if i["sector"] == sector]
    lines = [f"{sector} sector overview:"]
    for inst in sector_instruments:
        ticker_short = inst["ticker"].replace(".NS", "")
        signal_rows = (
            supabase.table("signals")
            .select("*")
            .eq("instrument_id", inst["id"])
            .order("event_time", desc=True)
            .limit(1)
            .execute()
            .data
        )
        signal = signal_rows[0] if signal_rows else None
        classification = (signal.get("explanation") or {}).get("classification") if signal else None
        if classification in ("HIGH", "MEDIUM"):
            lines.append(f"- {ticker_short}: {classification} activity (severity {signal['severity']})")
        else:
            lines.append(f"- {ticker_short}: nothing unusual")
    return "\n".join(lines)


def _summary_answer(instruments: list[dict]) -> str:
    signal_rows = supabase.table("signals").select("*").order("event_time", desc=True).execute().data
    latest_by_instrument = {}
    for row in signal_rows:
        latest_by_instrument.setdefault(row["instrument_id"], row)

    by_id = {inst["id"]: inst for inst in instruments}
    notable = [
        (by_id[iid]["ticker"].replace(".NS", ""), row)
        for iid, row in latest_by_instrument.items()
        if iid in by_id and (row.get("explanation") or {}).get("classification") in ("HIGH", "MEDIUM")
    ]

    if not notable:
        return "Nothing unusual has been detected across any of the 20 tracked stocks right now."

    notable.sort(key=lambda pair: pair[1]["severity"], reverse=True)
    lines = [
        f"{ticker}: {(row.get('explanation') or {}).get('classification')} severity {row['severity']}"
        for ticker, row in notable
    ]
    return "Here's what's currently notable: " + "; ".join(lines) + "."


def _fallback_help(instruments: list[dict]) -> str:
    tickers_list = ", ".join(i["ticker"].replace(".NS", "") for i in instruments)
    return (
        "I'm not sure I caught that. I can talk about the price, sector, or detected signals "
        f"for the stocks SignalGraph tracks ({tickers_list}), compare two or three of them, or "
        "give you a sector overview. Try things like \"how's Infosys doing?\", \"compare TCS "
        "and Wipro\", \"what's happening in banking?\", or a follow-up like \"what about its volume?\""
    )


def _rule_based_answer(message: str, history: list[dict]) -> str:
    if _is_advice_seeking(message):
        return NO_ADVICE_REPLY

    stripped = message.strip()
    short = len(stripped.split()) <= SHORT_MESSAGE_WORD_LIMIT
    if short and GREETING_PATTERN.match(stripped):
        return GREETING_REPLY
    if short and FAREWELL_PATTERN.match(stripped):
        return FAREWELL_REPLY
    if CAPABILITY_PATTERN.search(stripped):
        return CAPABILITY_REPLY
    if SEVERITY_PATTERN.search(stripped):
        return SEVERITY_REPLY
    if THANKS_PATTERN.search(stripped) and len(stripped.split()) <= 6:
        return "You're welcome! Anything else you'd like to know?"

    instruments = supabase.table("instruments").select("*").order("ticker").execute().data
    mentioned = _find_mentioned_instruments(message, instruments)
    focus = _detect_focus(message)

    if len(mentioned) >= 2:
        return _comparison_answer(mentioned[:3], focus)
    if len(mentioned) == 1:
        return _instrument_answer(mentioned[0], focus)

    sector = _find_mentioned_sector(message)
    if sector:
        return _sector_answer(sector, instruments)

    # No instrument or sector named directly — check whether this reads
    # like a follow-up ("what about its volume?") and, if so, recall the
    # instrument last discussed in this conversation.
    if (focus or _looks_like_followup(message)) and history:
        last_inst = _last_mentioned_instrument(history, instruments)
        if last_inst:
            return _instrument_answer(last_inst, focus)

    summary_keywords = ["today", "summary", "overview", "what's happening", "whats happening", "anything unusual", "any signals"]
    if any(kw in message.lower() for kw in summary_keywords):
        return _summary_answer(instruments)

    return _fallback_help(instruments)


def _build_snapshot() -> str:
    instruments = supabase.table("instruments").select("*").order("ticker").execute().data
    stats_rows = supabase.table("instrument_stats").select("*").execute().data
    stats_by_id = {row["instrument_id"]: row for row in stats_rows}

    signal_rows = supabase.table("signals").select("*").order("event_time", desc=True).execute().data
    latest_signal_by_id = {}
    for row in signal_rows:
        latest_signal_by_id.setdefault(row["instrument_id"], row)

    lines = []
    for inst in instruments:
        iid = inst["id"]
        stats = stats_by_id.get(iid)
        signal = latest_signal_by_id.get(iid)

        line = f"- {inst['ticker']} ({inst['name']}, sector: {inst['sector']}): "
        if stats and stats.get("last_price") is not None:
            line += f"last price {stats['last_price']}, as of {stats.get('last_event_time', 'unknown time')}"
        else:
            line += "no price data yet"

        if signal:
            explanation = signal.get("explanation") or {}
            reasons = "; ".join(explanation.get("reasons", [])) or "no specific reasons recorded"
            line += (
                f". Most recent detected signal: severity {signal['severity']} "
                f"({explanation.get('classification', 'unknown')}) at {signal['event_time']} — {reasons}"
            )
        else:
            line += ". No notable signal has been detected for this stock recently."

        lines.append(line)

    return "\n".join(lines)


def _llm_answer(message: str, history: list[dict]) -> str:
    import anthropic

    client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)
    snapshot = _build_snapshot()
    system_prompt = _LLM_SYSTEM_PROMPT_TEMPLATE.format(snapshot=snapshot)

    response = client.messages.create(
        model=MODEL,
        max_tokens=1024,
        system=system_prompt,
        messages=[*history, {"role": "user", "content": message}],
    )

    for block in response.content:
        if block.type == "text":
            return block.text
    return "I wasn't able to generate a response — please try rephrasing your question."


_LLM_SYSTEM_PROMPT_TEMPLATE = """You are SignalGraph's explain-only assistant. SignalGraph tracks a fixed universe of 20 NSE-listed Indian stocks and automatically detects unusual price, volume, and sector behavior for them.

Your job is to explain what has happened with these companies' stocks and why, using ONLY the live data snapshot given below. You can discuss: current price, sector, and — when one exists — the most recently detected signal for a stock (its severity, classification, and the specific reasons it fired: an unusual price move, a volume spike, divergence from its sector peers, or a structural high/low break).

STRICT RULES — follow every time, with no exceptions:
1. Never give investment advice of any kind. No buy/sell/hold recommendations, no price targets or predictions, no "is this a good investment" opinions, no suggestions shaped by risk tolerance or portfolio strategy. If asked for any of this, politely decline, explain that you only explain what already happened rather than advise what to do next, and suggest the user speak with a licensed financial advisor for that kind of question.
2. Only discuss the 20 companies in the snapshot below. If asked about a ticker or company not in this list, say plainly that it's outside SignalGraph's tracked universe.
3. Ground every factual claim in the snapshot data given to you. Never invent prices, news, or events. If the snapshot doesn't have what's needed to answer, say so directly instead of guessing.
4. Keep answers concise and conversational — this is a chat widget, not a report.

Live data snapshot (current as of this message):
{snapshot}
"""


def answer_question(message: str, history: list[dict]) -> str:
    """
    history: list of {"role": "user"|"assistant", "content": str}, oldest
    first, NOT including the current `message`. Used by both paths now:
    the rule-based engine scans it (most-recent-first) to recall which
    instrument was last discussed, so a follow-up like "what about its
    volume?" doesn't require repeating the ticker; the LLM path uses it
    for full conversational context when a key is configured.
    """
    if ANTHROPIC_API_KEY:
        return _llm_answer(message, history)
    return _rule_based_answer(message, history)
